---
ansible_user: root
icinga2_db: "icinga"
icinga2_db_pass: "icinga"
icinga2_db_user: "icinga"
icinga2_web2_db: "icingaweb"
icinga2_web2_db_pass: "icingaweb"
icinga2_web2_db_user: "icingaweb"
icinga2_db_host: 192.168.254.75