---
# handlers file for common tasks

- name: restart icinga2
  service: name=icinga2
           state=restarted
           enabled=yes

- name: reload icinga2
  service: name=icinga2
           state=reloaded
           enabled=yes
